[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL-Token 2022 Integration Tests"
edition = "2018"
license = "Apache-2.0"
name = "safe-token-2022-test"
repository = "https://github.com/fair-exchange/safecoin-program-library"
version = "0.0.1"

[features]
test-bpf = []

[build-dependencies]
walkdir = "2"

[dev-dependencies]
async-trait = "0.1"
safecoin-program = {path = "../../../Safecoin/sdk/program", version = "=1.10.34"}
safecoin-program-test = {path = "../../../Safecoin/program-test", version = "=1.10.34"}
safecoin-sdk = {path = "../../../Safecoin/sdk", version = "=1.10.34"}
safe-associated-token-account = { version = "1.0.5", path = "../../associated-token-account/program" }
safe-memo = { version = "3.0.8", path = "../../memo/program", features = ["no-entrypoint"] }
safe-token-2022 = { version = "0.2", path="../program-2022", features = ["no-entrypoint"] }
safe-token-client = { version = "0.0.1", path = "../client" }
