[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL-Token 2022 Integration Tests"
edition = "2018"
license = "Apache-2.0"
name = "safe-token-2022-test"
repository = "https://github.com/fair-exchange/safecoin-program-library"
version = "0.0.1"

[features]
test-sbf = []

[build-dependencies]
walkdir = "2"

[dev-dependencies]
async-trait = "0.1"
safecoin-program = "=1.11.6"
safecoin-program-test = "=1.11.6"
safecoin-sdk = "=1.11.6"
safe-associated-token-account = { version = "1.1", path = "../../associated-token-account/program" }
safe-memo = { version = "3.0.1", path = "../../memo/program", features = ["no-entrypoint"] }
safe-token-2022 = { version = "0.4", path="../program-2022", features = ["no-entrypoint"] }
safe-token-client = { version = "0.1.0", path = "../client" }
