[package]
name = "safe-token-swap-fuzz"
version = "0.0.1"
description = "Safecoin Program Library Token Swap Fuzzer"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin-program-library"
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
honggfuzz = { version = "0.5.55" }
arbitrary = { version = "1.0", features = ["derive"] }
safecoin-program = "1.11.6"
spl-math = { version = "0.1", path = "../../../libraries/math", features = [ "no-entrypoint" ] }
safe-token = { version = "3.5", path = "../../../token/program", features = [ "no-entrypoint" ] }
safe-token-swap = { path = "..", features = ["fuzz", "no-entrypoint"] }

[[bin]]
name = "token-swap-instructions"
path = "src/instructions.rs"
test = false
doc = false
