[package]
name = "test-client"
version = "0.1.0"
authors = ["Safecoin Labs Maintainers <maintainers@solanalabs.com>"]
publish = false
edition = "2021"

# Used to ensure that SPL programs are buildable by external clients

[dependencies]
safecoin-sdk = {path = "../../../Safecoin/sdk", version = "1.15.3"}
safe-memo = { path = "../../memo/program", features = [ "no-entrypoint" ] }
safe-token = { path = "../../token/program", features = [ "no-entrypoint" ] }
safe-token-swap = { path = "../../token-swap/program", features = [ "no-entrypoint" ] }
