[package]
name = "spl-governance-addin-mock"
version = "0.1.2"
description = "Safecoin Program Library Governance Voter Weight Addin Program"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.6"
bincode = "1.3.2"
borsh = "0.9.1"
num-derive = "0.3"
num-traits = "0.2"
serde = "1.0.127"
serde_derive = "1.0.103"
safecoin-program = {path = "../../../../Safecoin/sdk/program", version = "1.13.3"}
safe-token = { version = "3.5", path = "../../../token/program", features = [ "no-entrypoint" ] }
spl-governance-addin-api= { version = "0.1.2", path ="../../addin-api"}
spl-governance-tools= { version = "0.1.2", path ="../../tools"}
thiserror = "1.0"


[dev-dependencies]
assert_matches = "1.5.0"
base64 = "0.13"
proptest = "1.0"
safecoin-program-test = {path = "../../../../Safecoin/program-test", version = "1.13.3"}
safecoin-sdk = {path = "../../../../Safecoin/sdk", version = "1.13.3"}
spl-governance-test-sdk = { version = "0.1.2", path ="../../test-sdk"}


[lib]
crate-type = ["cdylib", "lib"]
