[package]
name = "spl-example-logging"
version = "1.0.0"
description = "Safecoin Program Library Logging Example"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin-program-library"
license = "Apache-2.0"
edition = "2018"
publish = false

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
safecoin-program = {version = "1.7.17"}

[dev-dependencies]
safecoin-program-test = {version = "1.7.17"}
safecoin-sdk = {version = "1.7.17"}

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
