anchor_version = "0.14.0"

[workspace]
members = ["program"]

[provider]
cluster = "devnet"
wallet = "~/.config/safecoin/id.json"

[programs.devnet]
safe-token-lending = "LENeX3L4CE1euBZp4zUNuicLP2SUZCbgXYZgBpZ9hWZ"