anchor_version = "0.24.2"
solana_version = "1.10.29"

[workspace]
members = [
  "governance/program",
  "memo/program",
  "stake-pool/program",
  "token/program",
  "token/program-2022",
]

[provider]
cluster = "mainnet"
wallet = "~/.config/safecoin/id.json"

[programs.mainnet]
spl_governance = "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw"
spl_stake_pool = "SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy"
safe_token = "ToKLx75MGim1d1jRusuVX8xvdvvbSDESVaNXpRA9PHN"
safe_token_2022 = "ZToGWcF1Qh9H7te1MmABiGsFUKvj5zXPQ2QnTqoHpHN"
