[package]
name = "safe-token-upgrade"
version = "0.1.0"
description = "Safecoin Program Library Token Upgrade"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.4"
safecoin-program = "1.11.6"
safe-token-2022 = { version = "0.4", path = "../../token/program-2022", features = ["no-entrypoint"] }
thiserror = "1.0"

[dev-dependencies]
safecoin-program-test = "1.11.6"
safecoin-sdk = "1.11.6"
safe-token = { version = "3.5", path = "../../token/program", features = ["no-entrypoint"] }
safe-token-client = { version = "0.1", path = "../../token/client" }
test-case = "2.2"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
