[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL Token Lending CLI"
edition = "2018"
homepage = "https://spl.solana.com/token-lending"
license = "Apache-2.0"
name = "safe-token-lending-cli"
repository = "https://github.com/fair-exchange/safecoin-program-library"
version = "0.2.0"

[dependencies]
clap = "2.33.3"
safecoin-clap-utils = {path = "../../../Safecoin/clap-utils", version = "=1.13.3"}
safecoin-cli-config = {path = "../../../Safecoin/cli-config", version = "=1.13.3"}
safecoin-client = {path = "../../../Safecoin/client", version = "=1.13.3"}
safecoin-logger = {path = "../../../Safecoin/logger", version = "=1.13.3"}
safecoin-sdk = {path = "../../../Safecoin/sdk", version = "=1.13.3"}
safecoin-program = {path = "../../../Safecoin/sdk/program", version = "=1.13.3"}
safe-token-lending = { version = "0.2", path="../program", features = [ "no-entrypoint" ] }
safe-token = { version = "3.5", path="../../token/program", features = [ "no-entrypoint" ]  }

[[bin]]
name = "safe-token-lending"
path = "src/main.rs"
