[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL Token Lending CLI"
edition = "2018"
homepage = "https://spl.solana.com/token-lending"
license = "Apache-2.0"
name = "safe-token-lending-cli"
repository = "https://github.com/fair-exchange/safecoin-program-library"
version = "0.1.0"

[dependencies]
clap = "2.33.3"
safecoin-clap-utils = {version = "1.8.12"}
safecoin-cli-config = {version = "1.8.12"}
safecoin-client = {version = "1.8.12"}
safecoin-logger = {version = "1.8.12"}
safecoin-sdk = {version = "1.8.12"}
safecoin-program = {version = "1.8.12"}
safe-token-lending = { path="../program", features = [ "no-entrypoint" ] }
safe-token = { path="../../token/program", features = [ "no-entrypoint" ]  }

[[bin]]
name = "safe-token-lending"
path = "src/main.rs"
