[package]
name = "spl-example-cross-program-invocation"
version = "1.0.0"
description = "Safecoin Program Library Cross Program Invocation Example"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin-program-library"
license = "Apache-2.0"
edition = "2018"
publish = false

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
safecoin-program = "1.10.8"

[dev-dependencies]
safecoin-program-test = "1.10.8"
safecoin-sdk = "1.10.8"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
