[package]
name = "safe-memo"
version = "3.0.8"
description = "Safecoin Program Library Memo"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
safecoin-program = {version = "1.10.34", path = "../../../Safecoin/sdk/program"}

[dev-dependencies]
safecoin-program-test = {version = "1.10.34", path="../../../Safecoin/program-test"}
safecoin-sdk = {path = "../../../Safecoin/sdk", version = "1.10.34"}

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
