[package]
name = "safe-memo"
version = "3.0.7"
description = "Safecoin Program Library Memo"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
safecoin-program = "1.10.32"

[dev-dependencies]
safecoin-program-test = "1.10.32"
safecoin-sdk = "1.10.32"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
