[package]
name = "safe-token"
version = "3.2.1"
description = "Safecoin Program Library Token"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin-program-library"
license = "Apache-2.0"
edition = "2018"
exclude = ["js/**"]

[features]
no-entrypoint = []

[dependencies]
arrayref = "0.3.6"
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.3"
safecoin-program = {version = "1.8.12", path = "../../../Safecoin/sdk/program"}
thiserror = "1.0"

[dev-dependencies]
safecoin-sdk = {version = "1.8.12", path = "../../../Safecoin/sdk"}

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
