[package]
name = "safe-token"
version = "3.3.3"
description = "Safecoin Program Library Token"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin-program-library"
license = "Apache-2.0"
edition = "2018"
exclude = ["js/**"]

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
arrayref = "0.3.6"
bytemuck = "1.7.2"
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.4"
safecoin-program = {version = "1.10.34", path = "../../../Safecoin/sdk/program"}
thiserror = "1.0"

[dev-dependencies]
lazy_static = "1.4.0"
serial_test = "0.5.1"
safecoin-program-test = {version = "1.10.34", path = "../../../Safecoin/program-test"}
safecoin-sdk = {version = "1.10.34", path = "../../../Safecoin/sdk"}

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
