[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL-Token Command-line Utility"
edition = "2018"
homepage = "https://spl.solana.com/token"
license = "Apache-2.0"
name = "safe-token-cli"
repository = "https://github.com/fair-exchange/safecoin-program-library"
version = "2.0.15"

[build-dependencies]
walkdir = "2"

[dependencies]
clap = "2.33.3"
console = "0.14.0"
indicatif = "0.16.2"
serde = "1.0.130"
serde_derive = "1.0.103"
serde_json = "1.0.68"
safecoin-account-decoder = "=1.10.32"
safecoin-clap-utils = "=1.10.32"
safecoin-cli-config = "=1.10.32"
safecoin-cli-output = "=1.10.32"
safecoin-client = "=1.10.32"
safecoin-logger = "=1.10.32"
safecoin-remote-wallet = "=1.10.32"
safecoin-sdk = "=1.10.32"
safecoin-transaction-status = "=1.10.32"
safe-token = { version = "3.3", path="../program", features = [ "no-entrypoint" ] }
safe-associated-token-account = { version = "1.0.5", path="../../associated-token-account/program", features = [ "no-entrypoint" ] }
safe-memo = { version = "3.0.1", path="../../memo/program", features = ["no-entrypoint"] }

[dev-dependencies]
safecoin-test-validator = "=1.10.32"

[[bin]]
name = "safe-token"
path = "src/main.rs"
