[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL-Token Command-line Utility"
edition = "2018"
homepage = "https://spl.solana.com/token"
license = "Apache-2.0"
name = "safe-token-cli"
repository = "https://github.com/fair-exchange/safecoin-program-library"
version = "2.0.14"

[dependencies]
clap = "2.33.3"
console = "0.14.0"
serde = "1.0.127"
serde_derive = "1.0.103"
serde_json = "1.0.66"
safecoin-account-decoder = {version = "=1.8.12"}
safecoin-clap-utils = {version = "=1.8.12"}
safecoin-cli-config = {version = "=1.8.12"}
safecoin-cli-output = {version = "=1.8.12"}
safecoin-client = {version = "=1.8.12"}
safecoin-logger = {version = "=1.8.12"}
safecoin-remote-wallet = {version = "=1.8.12"}
safecoin-sdk = {version = "=1.8.12"}
safe-token = { version = "3.2.2", path="../program", features = [ "no-entrypoint" ] }
safe-associated-token-account = { version = "1.0.10", path="../../associated-token-account/program", features = [ "no-entrypoint" ] }
safe-memo = { version = "3.0.6", path="../../memo/program", features = ["no-entrypoint"] }

[[bin]]
name = "safe-token"
path = "src/main.rs"
