[package]
authors = ["Safecoin Labs Maintainers <maintainers@solanalabs.com>"]
description = "SPL-Token Command-line Utility"
edition = "2021"
homepage = "https://spl.solana.com/token"
license = "Apache-2.0"
name = "safe-token-cli"
repository = "https://github.com/fair-exchange/safecoin-program-library"
version = "2.2.0"

[build-dependencies]
walkdir = "2"

[dependencies]
clap = "2.33.3"
console = "0.15.0"
indicatif = "0.16.2"
serde = "1.0.130"
serde_derive = "1.0.103"
serde_json = "1.0.68"
safecoin-account-decoder = {path = "../../../Safecoin/account-decoder", version = "=1.15.3"}
safecoin-clap-utils = {path = "../../../Safecoin/clap-utils", version = "=1.15.3"}
safecoin-cli-config = {path = "../../../Safecoin/cli-config", version = "=1.15.3"}
safecoin-cli-output = {path = "../../../Safecoin/cli-output", version = "=1.15.3"}
safecoin-client = {path = "../../../Safecoin/client", version = "=1.15.3"}
safecoin-logger = {path = "../../../Safecoin/logger", version = "=1.15.3"}
safecoin-remote-wallet = {path = "../../../Safecoin/remote-wallet", version = "=1.15.3"}
safecoin-sdk = {path = "../../../Safecoin/sdk", version = "=1.15.3"}
safecoin-transaction-status = {path = "../../../Safecoin/transaction-status", version = "=1.15.3"}
safe-token = { version = "3.5", path="../program", features = [ "no-entrypoint" ] }
safe-token-2022 = { version = "0.5", path="../program-2022", features = [ "no-entrypoint" ] }
safe-token-client = { version = "0.3", path="../client" }
safe-associated-token-account = { version = "1.1", path="../../associated-token-account/program", features = [ "no-entrypoint" ] }
safe-memo = { version = "3.0.1", path="../../memo/program", features = ["no-entrypoint"] }
strum = "0.24"
strum_macros = "0.24"
tokio = "1.14"

[dev-dependencies]
safecoin-test-validator = {path = "../../../Safecoin/test-validator", version = "=1.15.3"}
assert_cmd = "2.0.4"
serial_test = "0.8.0"
tempfile = "3.3.0"

[[bin]]
name = "safe-token"
path = "src/main.rs"
