[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL-Token Command-line Utility"
edition = "2018"
homepage = "https://spl.solana.com/token"
license = "Apache-2.0"
name = "safe-token-cli"
repository = "https://github.com/fair-exchange/safecoin-program-library"
version = "2.0.16"

[build-dependencies]
walkdir = "2"

[dependencies]
clap = "2.33.3"
console = "0.14.0"
indicatif = "0.16.2"
serde = "1.0.130"
serde_derive = "1.0.103"
serde_json = "1.0.68"
safecoin-account-decoder = "=1.11.6"
safecoin-clap-utils = "=1.11.6"
safecoin-cli-config = "=1.11.6"
safecoin-cli-output = "=1.11.6"
safecoin-client = "=1.11.6"
safecoin-logger = "=1.11.6"
safecoin-remote-wallet = "=1.11.6"
safecoin-sdk = "=1.11.6"
safecoin-transaction-status = "=1.11.6"
safe-token = { version = "3.5", path="../program", features = [ "no-entrypoint" ] }
safe-token-2022 = { version = "0.4", path="../program-2022", features = [ "no-entrypoint" ] }
safe-token-client = { version = "0.1", path="../client" }
safe-associated-token-account = { version = "1.1", path="../../associated-token-account/program", features = [ "no-entrypoint" ] }
safe-memo = { version = "3.0.1", path="../../memo/program", features = ["no-entrypoint"] }
strum = "0.24"
strum_macros = "0.24"
tokio = "1.14"

[dev-dependencies]
safecoin-test-validator = "=1.11.6"
assert_cmd = "2.0.4"
serial_test = "0.8.0"
tempfile = "3.3.0"

[[bin]]
name = "safe-token"
path = "src/main.rs"
