[package]
name = "spl-shared-memory"
version = "2.0.6"
description = "Safecoin Program Library Shared-memory"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
test-bpf = []

[dependencies]
arrayref = "0.3.6"
safecoin-program = {version = "=1.8.12", path = "../../../Safecoin/sdk/program"}

[dev-dependencies]
safecoin-program-test = {version = "=1.8.12", path = "../../../Safecoin/program-test"}
safecoin-sdk = {version = "=1.8.12", path = "../../../Safecoin/sdk"}

[lib]
crate-type = ["cdylib", "lib"]
