[package]
name = "stateless-asks"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
no-entrypoint = []
test-bpf = []

[dependencies]
borsh = "0.9.1"
safecoin-program = {path = "../../../Safecoin/sdk/program", version = "1.9.29"}
safe-token = { version = "3.2", path = "../../token/program", features = ["no-entrypoint"] }
safe-associated-token-account = {path = "../../associated-token-account/program", version = "1.0.11", features = ["no-entrypoint"]}
thiserror = "1.0"

[dev-dependencies]
safecoin-program-test = {path = "../../../Safecoin/program-test", version = "1.9.29"}
safecoin-sdk = {path = "../../../Safecoin/sdk", version = "1.9.29"}

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
