[package]
name = "spl-example-transfer-lamports"
version = "1.0.0"
description = "Safecoin Program Library Transfer Lamports Example"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
safecoin-program = {path = "../../../Safecoin/sdk/program", version = "1.13.3"}

[dev-dependencies]
safecoin-program-test = {path = "../../../Safecoin/program-test", version = "1.13.3"}
safecoin-sdk = {path = "../../../Safecoin/sdk", version = "1.13.3"}

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
