[package]
name = "spl-example-transfer-lamports"
version = "1.0.0"
description = "Safecoin Program Library Transfer Lamports Example"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
safecoin-program = {version = "1.7.17", path = "../../../../Safecoin/sdk/program"}

[dev-dependencies]
safecoin-program-test = {version = "1.7.17", path = "../../../../Safecoin/program-test"}
safecoin-sdk = {version = "1.7.17", path = "../../../../Safecoin/sdk"}

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
