[package]
name = "spl-record"
version = "0.1.0"
description = "Safecoin Program Library Record Program"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
borsh = "0.9.1"
borsh-derive = "0.9.0"
num-derive = "0.3"
num-traits = "0.2"
safecoin-program = {version = "1.7.17", path = "../../../Safecoin/sdk/program"}
thiserror = "1.0"

[dev-dependencies]
safecoin-program-test = {version = "1.7.17", path = "../../../Safecoin/program-test"}
safecoin-sdk = {version = "1.7.17", path = "../../../Safecoin/sdk"}

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
