[package]
name = "safe-token-2022"
version = "0.2.0"
description = "Safecoin Program Library Token 2022"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin-program-library"
license = "Apache-2.0"
edition = "2018"
exclude = ["js/**"]

[features]
no-entrypoint = []
test-bpf = []
# Remove these features once the underlying syscalls are released on all networks
default = ["reallocate", "sibling-instruction", "zk-ops"]
reallocate = []
sibling-instruction = []
zk-ops = []

[dependencies]
arrayref = "0.3.6"
bytemuck = { version = "1.7.2", features = ["derive"] }
num-derive = "0.3"
num-traits = "0.2"
num_enum = "0.5.4"
safecoin-program = {path = "../../../Safecoin/sdk/program", version = "1.10.32"}
safe-zk-token-sdk = {path = "../../../Safecoin/zk-token-sdk", version = "1.10.32"}
safe-memo = { version = "3.0.7", path = "../../memo/program", features = [ "no-entrypoint" ] }
safe-token = { version = "3.3",  path = "../program", features = ["no-entrypoint"] }
thiserror = "1.0"

[dev-dependencies]
lazy_static = "1.4.0"
serial_test = "0.5.1"
safecoin-program-test = {path = "../../../Safecoin/program-test", version = "1.10.32"}
safecoin-sdk = {path = "../../../Safecoin/sdk", version = "1.10.32"}

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
