[package]
name = "safe-token-upgrade-cli"
version = "0.1.0"
description = "SPL Token Upgrade Command-line Utility"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin-program-library"
license = "Apache-2.0"
edition = "2018"

[build-dependencies]
walkdir = "2"

[dependencies]
clap = { version = "3", features = ["cargo"] }
futures-util = "0.3.19"
solana-clap-v3-utils = "1.14.3"
safecoin-cli-config = {path = "../../../Safecoin/cli-config", version = "1.14.3"}
safecoin-client = {path = "../../../Safecoin/client", version = "1.14.3"}
safecoin-logger = {path = "../../../Safecoin/logger", version = "1.14.3"}
safecoin-remote-wallet = "1.14.3"
safecoin-sdk = {path = "../../../Safecoin/sdk", version = "1.14.3"}
safe-associated-token-account = { version = "1.1", path = "../../associated-token-account/program", features = ["no-entrypoint"] }
safe-token = { version = "3.5", path = "../../token/program", features = ["no-entrypoint"] }
safe-token-2022 = { version = "0.4", path = "../../token/program-2022", features = ["no-entrypoint"] }
safe-token-client = { version = "0.1", path = "../../token/client" }
safe-token-upgrade = { version = "0.1", path = "../program", features = ["no-entrypoint"] }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
safecoin-test-validator = "1.14.3"

[[bin]]
name = "safe-token-upgrade"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
