[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL-Token Rust Client"
edition = "2018"
license = "Apache-2.0"
name = "safe-token-client"
repository = "https://github.com/fair-exchange/safecoin-program-library"
version = "0.0.1"

[dependencies]
async-trait = "0.1"
safecoin-client = "=1.10.8"
safecoin-program-test = "=1.10.8"
safecoin-sdk = "=1.10.8"
# We never want the entrypoint for ATA, but we want the entrypoint for token when
# testing token
safe-associated-token-account = { version = "1.0.5", path = "../../associated-token-account/program", features = ["no-entrypoint"] }
safe-memo = { version = "3.0.1", path = "../../memo/program", features = ["no-entrypoint"] }
safe-token-2022 = { version = "0.2", path="../program-2022" }
thiserror = "1.0"
