[package]
authors = ["Safecoin Labs Maintainers <maintainers@solanalabs.com>"]
description = "SPL-Token Rust Client"
edition = "2021"
license = "Apache-2.0"
name = "safe-token-client"
repository = "https://github.com/fair-exchange/safecoin-program-library"
version = "0.3.0"

[dependencies]
async-trait = "0.1"
safecoin-cli-output = {path = "../../../Safecoin/cli-output", version = "=1.14.17", optional = true }
safecoin-client = {path = "../../../Safecoin/client", version = "=1.14.17"}
safecoin-program-test = {path = "../../../Safecoin/program-test", version = "=1.14.17"}
safecoin-sdk = {path = "../../../Safecoin/sdk", version = "=1.14.17"}
# We never want the entrypoint for ATA, but we want the entrypoint for token when
# testing token
safe-associated-token-account = { version = "1.1", path = "../../associated-token-account/program", features = ["no-entrypoint"] }
safe-memo = { version = "3.0.1", path = "../../memo/program", features = ["no-entrypoint"] }
safe-token = { version = "3.5", path="../program", features = [ "no-entrypoint" ] }
safe-token-2022 = { version = "0.5", path="../program-2022" }
thiserror = "1.0"

[features]
default = ["display"]
display = ["dep:safecoin-cli-output"]
