[package]
name = "spl-binary-oracle-pair"
version = "0.1.0"
description = "Safecoin Program Library Binary Oracle Pair"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/fair-exchange/safecoin-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
test-bpf = []

[dependencies]
num-derive = "0.3"
num-traits = "0.2"
safecoin-program = {version = "1.8.12", path = "../../../Safecoin/sdk/program"}
safe-token = { version = "3.2.2", path = "../../token/program", features = [ "no-entrypoint" ] }
thiserror = "1.0"
uint = "0.9"
arbitrary = { version = "0.4", features = ["derive"], optional = true }
borsh = "0.9.1"

[dev-dependencies]
safecoin-program-test = {version = "1.8.12", path = "../../../Safecoin/program-test"}
safecoin-sdk = {version = "1.8.12", path = "../../../Safecoin/sdk"}

[lib]
crate-type = ["cdylib", "lib"]
