[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL-Stake-Pool Command-line Utility"
edition = "2018"
homepage = "https://spl.solana.com/stake-pool"
license = "Apache-2.0"
name = "spl-stake-pool-cli"
repository = "https://github.com/fair-exchange/safecoin-program-library"
version = "0.4.0"

[dependencies]
borsh = "0.9"
clap = "2.33.3"
serde_json = "1.0.66"
safecoin-account-decoder = {version = "=1.8.12"}
safecoin-clap-utils = {version = "=1.8.12"}
safecoin-cli-config = {version = "=1.8.12"}
safecoin-client = {version = "=1.8.12"}
safecoin-logger = {version = "=1.8.12"}
safecoin-program = {version = "=1.8.12"}
safecoin-remote-wallet = {version = "=1.8.12"}
safecoin-sdk = {version = "=1.8.12"}
safe-associated-token-account = { version = "1.0.10", path="../../associated-token-account/program", features = [ "no-entrypoint" ] }
spl-stake-pool = { version = "0.4", path="../program", features = [ "no-entrypoint" ] }
safe-token = { version = "3.2.2", path="../../token/program", features = [ "no-entrypoint" ]  }
bs58 = "0.4.0"
bincode = "1.3.1"
lazy_static = "1.4.0"

[[bin]]
name = "spl-stake-pool"
path = "src/main.rs"
