[package]
name = "safe_token_perf_monitor"
version = "0.0.1"
description = "SPL Token performance monitor"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/fair-exchange/safecoin-program-library"
license = "Apache-2.0"
edition = "2018"

[dev-dependencies]
rand = { version = "0.7.0"}
safe-token = { path = "../program", features = [ "no-entrypoint" ] }
safecoin-runtime = "1.7.7"
safecoin-sdk = "1.7.7"
safecoin-bpf-loader-program = "1.7.7"
solana_rbpf = "0.2"

[workspace]
